openapi: 3.0.0

info:
  title: App Invite Service
  description: A service that facilitates the invite token generation and validation for the Catalyst Experience App
  version: 0.0.1

servers:
  - url: http://localhost:8080
    description: Local Development environment

paths:
  /generate:
    get:
      security:
        - basicAuth: []

      summary: Generate token
      description: Generate token that can be used for validation in the Catalyst Experience App
      operationId: Generate

      responses:
        "200":
          description: A JSON object containing the token
          content:
            application/json:
              schema:
                type: object

        "401":
          description: A JSON object requesting the client to provide Authorization data

          headers:
            WWW-Authenticate:
              schema:
                type: string

          content:
            application/json:
              schema:
                type: object

  /validate/{token}:
    get:
      summary: Validate token
      description: Validate a token, it can be used to login
      operationId: ValidateToken

      parameters:
        - in: path
          name: token
          schema:
            type: string
          required: true
          description: The token to be validated

      responses:
        "200":
          description: A JSON object indicating success or failure
          content:
            application/json:
              schema:
                type: object

  /recall/{token}:
    get:
      security:
        - basicAuth: []

      summary: Disable a token
      description: Disable(recall) a token
      operationId: RecallToken

      parameters:
        - in: path
          name: token
          schema:
            type: string
          required: true
          description: The token to be recalled

      responses:
        "200":
          description: A JSON object indicating success or failure
          content:
            application/json:
              schema:
                type: object

        "404":
          description: A JSON object indicating the token was not found
          content:
            application/json:
              schema:
                type: object

        "401":
          description: A JSON object requesting the client to provide Authorization data

          headers:
            WWW-Authenticate:
              schema:
                type: string

          content:
            application/json:
              schema:
                type: object

  /active:
    get:
      security:
        - basicAuth: []

      summary: List all active tokens
      description: List tokens  that have not expired or recalled
      operationId: ActiveTokens

      responses:
        "200":
          description: A JSON object containing an array of token objects
          content:
            application/json:
              schema:
                type: object

        "404":
          description: A JSON object indicating the tokens were not found
          content:
            application/json:
              schema:
                type: object

        "401":
          description: A JSON object requesting the client to provide Authorization data

          headers:
            WWW-Authenticate:
              schema:
                type: string

          content:
            application/json:
              schema:
                type: object

  /inactive:
    get:
      security:
        - basicAuth: []

      summary: List all inactive tokens
      description: List tokens  that have expired/recalled
      operationId: InactiveTokens

      responses:
        "200":
          description: A JSON object containing an array of token objects
          content:
            application/json:
              schema:
                type: object

        "404":
          description: A JSON object indicating the tokens were not found
          content:
            application/json:
              schema:
                type: object

        "401":
          description: A JSON object requesting the client to provide Authorization data

          headers:
            WWW-Authenticate:
              schema:
                type: string

          content:
            application/json:
              schema:
                type: object

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
